version: '3'
services:
  dashapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9002:9000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
    volumes:
      - ../logRepository:/logRepository
    networks:
      - mongoDbDash
  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
    networks:
      - mongoDbDash

networks:
  mongoDbDash:
    driver: bridge