version: '3'
services:
  dashapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9002:9000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db